### ISSUE TITLE
Not working on Cinnamon 2.4.3

### ISSUE THREAD

**Issue by varlesh** [ronaldoats/SensorsFans_Cinnamon#1]
Hello.
Linux Mint Cinnamon 17.1
lm-sensors installed, detect and worked.
Screen:
http://itmag.es/3xjrv
Log:
`error t=2014-11-18T21:04:00Z Expected type utf8 for Argument 'text' but got type 'object'
info t=2014-11-18T21:04:00Z Loaded applet sensorsFans@bi-ni.com in 35 ms`

**Comment by ronaldoats** [comment]
sudo modprobe i8k force=1
sensors

**Comment by ronaldoats** [comment]
Modo Permanente.

<div style="background: #202020; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #d0d0d0">sudo</span> <span style="color: #d0d0d0">nano</span> <span style="color: #ed9d13">/etc/rc.local</span>
</pre></div>

Anexar esto:

<div style="background: #202020; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #d0d0d0">modprobe</span> <span style="color: #d0d0d0">i8k</span> <span style="color: #d0d0d0">force=</span><span style="color: #3677a9">1</span>
</pre></div>

**Comment by varlesh** [comment]
Thx. Working :)
